//test_str_t data[] = {
//   no.        text,tlen,       regexp,rlen,        {bstr,len},...         nmatch,expect,cflags,eflags,on_syntax,off_syntax,start,end
    {__LINE__, {"abc"},         {"a"},              {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"b"},              {{"b"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"c"},              {{"c"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"d"},              {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"ab"},             {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"bc"},             {{"bc"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"ac"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"cd"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"abc"},            {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {""},               {{""}},                 1, 0, REG_ALL},
    {__LINE__, {""},            {""},               {{""}},                 1, 0, REG_ALL},

    {__LINE__, {"abc"},         {"^a"},             {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a$"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"^b"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"b$"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"c$"},             {{"c"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^ab"},            {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^bc"},            {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"ab$"},            {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"bc$"},            {{"bc"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^ab$"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"^bc$"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"^abc$"},          {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"^abc"},        {"^^a"},            {{"^a"}},               1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"^^a"},            {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"abc$"},        {"c$$"},            {{"c$"}},               1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"c$$"},            {{"c"}},                1, 0, REG_EXT},

    {__LINE__, {"abc"},         {"a*"},             {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"aa*"},            {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"aac"},         {"aa*"},            {{"aa"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"ab*c"},           {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"b*"},             {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"bc*"},            {{"bc"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"d*"},             {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^a*"},            {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^b*"},            {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^c*"},            {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^d*"},            {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a*$"},            {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"aaabbbccc"},   {"aaaa*"},          {{"aaa"}},              1, 0, REG_ALL},
    {__LINE__, {"aaabbbccc"},   {"ab*"},            {{"a"}},                1, 0, REG_ALL},

    {__LINE__, {"abc"},         {"."},              {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {".."},             {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"..."},            {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"...."},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"^...$"},          {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a.c"},            {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"^a.c$"},          {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a..c"},           {{""}},                 1, 1, REG_ALL},

    {__LINE__, {"abc  xyz"},    {"abc *xyz"},       {{"abc  xyz"}},         1, 0, REG_ALL},
    {__LINE__, {"*"},           {"*"},              {{"*"}},                1, 0, REG_BRE},
    {__LINE__, {"*"},           {"^*"},             {{"*"}},                1, 0, REG_BRE},
    {__LINE__, {"**"},          {"**"},             {{"**"}},               1, 0, REG_BRE},
    {__LINE__, {"*"},           {"*"},              {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"*"},           {"^*"},             {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"**"},          {"**"},             {{""}},                 1,-1, REG_EXT},

    {__LINE__, {"a*c"},         {"\\*"},            {{"*"}},                1, 0, REG_ALL},
    {__LINE__, {"a*c"},         {"\\*\\*"},         {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"a**c"},        {"\\*\\*"},         {{"**"}},               1, 0, REG_ALL},
    {__LINE__, {"a**c"},        {"^a\\*\\*c$"},     {{"a**c"}},             1, 0, REG_ALL},
    {__LINE__, {"a\\c"},        {"\\\\"},           {{"\\"}},               1, 0, REG_ALL},
    {__LINE__, {"a\\b\\c"},     {"\\\\b\\\\"},      {{"\\b\\"}},            1, 0, REG_ALL},
    {__LINE__, {"a..c"},        {"a\\.\\.c"},       {{"a..c"}},             1, 0, REG_ALL},
    {__LINE__, {"a$c"},         {"a\\$"},           {{"a$"}},               1, 0, REG_ALL},
    {__LINE__, {"a$c"},         {"c\\$"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"a$c"},         {"a$c"},            {{"a$c"}},              1, 0, REG_BRE}, //BREでは^,$は最初、最後だけ特殊な意味を持つ
    {__LINE__, {"$bc"},         {"$b"},             {{"$b"}},               1, 0, REG_BRE},
    {__LINE__, {"a$c"},         {"a$c"},            {{""}},                 1, 1, REG_EXT}, //EREでは~,$は常に特殊な意味を持つ
    {__LINE__, {"$bc"},         {"$b"},             {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"\\abc"},       {"\\a"},            {{"a"}},                1, 0, REG_GNU},
    {__LINE__, {"\\abc"},       {"\\i"},            {{""}},                 1,-1, REG_PCRE2},   //PCRE2では不正なエスケープ指定はエラーになる
    {__LINE__, {"^abc"},        {"^a"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"a^bc"},        {"\\^b"},           {{"^b"}},               1, 0, REG_ALL},
    {__LINE__, {"a^bc"},        {"a^b"},            {{"a^b"}},              1, 0, REG_BRE},
    {__LINE__, {"a^bc"},        {"a^b"},            {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"a**"},            {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"abc"},         {"a**"},            {{"a"}},                1, 0, REG_EXT},//EREでは多重repeatが許される
    {__LINE__, {"abc"},         {".*"},             {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a.*"},            {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a.*c"},           {{"abc"}},              1, 0, REG_ALL},

    {__LINE__, {"abc"},         {"a\\?"},           {{"a"}},                1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"a\\+"},           {{"a"}},                1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"a\\?b"},          {{"ab"}},               1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"a\\+b"},          {{"ab"}},               1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"a?"},             {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a+"},             {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a?b"},            {{"ab"}},               1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a+b"},            {{"ab"}},               1, 0, REG_EXT},
    {__LINE__, {"a?+"},         {"?+"},             {{"?+"}},               1, 0, REG_BRE},
    {__LINE__, {"a?+"},         {"\\?\\+"},         {{"?+"}},               1, 0, REG_EXT},

    {__LINE__, {"abc"},         {"[a]"},            {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a[ab]"},          {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a[abc]c"},        {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[a"},             {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"abc"},         {"[^a]"},           {{"b"}},                1, 0, REG_ALL},
    {__LINE__, {"aaa"},         {"[^a]"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"[^abc]"},         {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"[^]"},            {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"^a"},          {"[^^]"},           {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"]"},           {"[]]"},            {{"]"}},                1, 0, REG_ALL},
    {__LINE__, {"-"},           {"[-]"},            {{"-"}},                1, 0, REG_ALL},
    {__LINE__, {"-"},           {"[a-]"},           {{"-"}},                1, 0, REG_ALL},
    {__LINE__, {"-]"},          {"[]-]*"},          {{"-]"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[a-c]"},          {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[c-a]"},          {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"abc"},         {"[a-a]"},          {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[x-z]"},          {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"[0-9]"},          {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"123"},         {"[0-9]"},          {{"1"}},                1, 0, REG_ALL},
    {__LINE__, {"abc/5"},       {"[a-z]/[0-9]"},    {{"c/5"}},              1, 0, REG_ALL},
    {__LINE__, {"abc/z5"},      {"[a-z]/[0-9]"},    {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc"},         {"[a-c-e]"},        {{""}},                 1,-1, REG_ALL},

    {__LINE__, {"abc"},         {"[b]*"},           {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[b]*c"},          {{"bc"}},               1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"a[b]*c"},         {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abbc"},        {"a[b-c]*[a-b]*c"}, {{"abbc"}},             1, 0, REG_ALL},

    {__LINE__, {"abc"},         {"a\\{1\\}"},       {{"a"}},                1, 0, REG_BRE},
    {__LINE__, {"abc"},         {"a{1}"},           {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a{1,}"},          {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a{2,}"},          {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"aabc"},        {"a{2,}"},          {{"aa"}},               1, 0, REG_EXT},
    {__LINE__, {"baaac"},       {"a{2,}"},          {{"aaa"}},              1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"\\{1\\}"},        {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"abc"},         {"{1}"},            {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{1b}"},          {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{1,b}"},         {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{1,2"},          {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{2,1}"},         {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{0}"},           {{""}},                 1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a{0,0}"},         {{""}},                 1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a{,1}"},          {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"a}"},          {"\\}"},            {{"}"}},                1, 0, REG_BRE},
    {__LINE__, {"{"},           {"\\{"},            {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"{}"},          {"{}"},             {{"{}"}},               1, 0, REG_BRE},
    {__LINE__, {"a}"},          {"}"},              {{"}"}},                1, 0, REG_EXT},
    {__LINE__, {"{"},           {"{"},              {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"{}"},          {"\\{\\}"},         {{"{}"}},               1, 0, REG_EXT},

    {__LINE__, {"1234567"},     {"[0-9]\\{2\\}\\{3\\}"},  {{""}},           1,-1, REG_BRE},
    {__LINE__, {"1234567"},     {"[0-9]{2}{3}"},    {{"123456"}},           1, 0, REG_EXT},//EREでは多重repeatが許される
    {__LINE__, {"1234567"},     {"([0-9]{2}){3}"},  {{"123456"},{"56"}},    2, 0, REG_EXT},
    {__LINE__, {"1234567"},     {"[3-9]{2}+"},      {{"3456"}},             1, 0, REG_EXT},
    {__LINE__, {"1234567"},     {"[3-9]{2}{3}"},    {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"aaaaa"},       {"a{2}+"},          {{"aaaa"}},             1, 0, REG_EXT},
    {__LINE__, {"aaaaaaa"},     {"a{2,4}+"},        {{"aaaaaaa"}},          1, 0, REG_EXT},
    {__LINE__, {"aaaaaaaa"},    {"^a{2,4}+$"},      {{"aaaaaaaa"}},         1, 0, REG_EXT},

    {__LINE__, {"abc"},         {"a{0,32768}"},     {{"a"}},                1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"a{32768}"},       {{"a"}},                1,-1, REG_EXT},

    {__LINE__, {"abc"},         {"[a-z]{3}"},       {{"abc"}},              1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"[a-z]{4}"},       {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"[a-z]{3,4}"},     {{"abc"}},              1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"[a-z]{4,5}"},     {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {".{3}"},           {{"abc"}},              1, 0, REG_EXT},
    {__LINE__, {"abc"},         {".{4}"},           {{""}},                 1, 1, REG_EXT},

//   no.        text,tlen,       regexp,rlen,        {bstr,len},...         nmatch,expect,cflags,eflags,on_syntax,off_syntax,start,end
    {__LINE__, {"abc"},         {"\\(a\\)"},        {{"a"},{"a"}},          2, 0, REG_BRE},
    {__LINE__, {"abc"},         {"(a)"},            {{"a"},{"a"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(c)"},            {{"c"},{"c"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(abc)"},          {{"abc"},{"abc"}},      2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"^(a)"},           {{"a"},{"a"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(c)$"},           {{"c"},{"c"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"^(abc)$"},        {{"abc"},{"abc"}},      2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"([bc])"},         {{"b"},{"b"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a([bc]*)"},       {{"abc"},{"bc"}},       2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"a(.)*"},          {{"abc"},{"c"}},        2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"\\(a\\)\\(bc\\)"},{{"abc"},{"a"},{"bc"}}, 3, 0, REG_BRE},
    {__LINE__, {"abc"},         {"(a)(bc)"},        {{"abc"},{"a"},{"bc"}}, 3, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(a)(b)(c)"},      {{"abc"},{"a"},{"b"},{"c"}},4, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(...)"},          {{"abc"},{"abc"}},      2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"([a-z]{1,3})"},   {{"abc"},{"abc"}},      2, 0, REG_EXT},
    {__LINE__, {"a*c"},         {"\\(*\\)"},        {{"*"}},                1, 0, REG_BRE},
    {__LINE__, {"a*c"},         {"(*)"},            {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"a+c"},         {"\\(\\+\\)"},      {{"+"}},                1, 0, REG_BRE},
    {__LINE__, {"a+c"},         {"(+)"},            {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"a?c"},         {"\\(\\?\\)"},      {{"?"}},                1, 0, REG_BRE},
    {__LINE__, {"a?c"},         {"(?)"},            {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"*bc"},         {"\\(^*b\\)"},      {{"*b"}},               1, 0, REG_BRE},
    {__LINE__, {"*bc"},         {"(^*b)"},          {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"+bc"},         {"\\(^\\+b\\)"},    {{"+b"}},               1, 0, REG_BRE},
    {__LINE__, {"+bc"},         {"(^+b)"},          {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"?bc"},         {"\\(^\\?b\\)"},    {{"?b"}},               1, 0, REG_BRE},
    {__LINE__, {"?bc"},         {"(^?b)"},          {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"(a)"},         {"\\(a"},           {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"(a)"},         {"a\\)"},           {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"(a)"},         {"a)"},             {{"a)"}},               1, 0, REG_EXT},    //???
    {__LINE__, {"(a)"},         {"(a"},             {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abc"},         {"\\(\\)"},         {{""},{""}},            2, 0, REG_BRE},
    {__LINE__, {"abc"},         {"()"},             {{""},{""}},            2, 0, REG_EXT},

    {__LINE__, {"abc"},         {"\\(^a\\)b"},      {{"ab"},{"a"}},         2, 0, REG_BRE},
    {__LINE__, {"0abc"},        {"\\(^a\\)b"},      {{""}},                 1, 1, REG_BRE},
    {__LINE__, {"abc"},         {"b\\(c$\\)"},      {{"bc"},{"c"}},         2, 0, REG_BRE},
    {__LINE__, {"abcd"},        {"b\\(c$\\)"},      {{""}},                 1, 1, REG_BRE},
    {__LINE__, {"abc"},         {"\\(^abc$\\)"},    {{"abc"},{"abc"}},      2, 0, REG_BRE},
    {__LINE__, {"abcd"},        {"\\(^abc$\\)"},    {{""}},                 1, 1, REG_BRE},
    {__LINE__, {"abcd"},        {"\\(^abc$\\)d"},   {{""}},                 1, 1, REG_BRE},
    {__LINE__, {"abc"},         {"\\(^[abc]*$\\)"}, {{"abc"},{"abc"}},      2, 0, REG_BRE},
    {__LINE__, {"abc"},         {"(^a)b"},          {{"ab"},{"a"}},         2, 0, REG_EXT},
    {__LINE__, {"0abc"},        {"(^a)b"},          {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"b(c$)"},          {{"bc"},{"c"}},         2, 0, REG_EXT},
    {__LINE__, {"abcd"},        {"b(c$)"},          {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"(^abc$)"},        {{"abc"},{"abc"}},      2, 0, REG_EXT},
    {__LINE__, {"abcd"},        {"(^abc$)"},        {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abcd"},        {"(^abc$)d"},       {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"(^[abc]*$)"},     {{"abc"},{"abc"}},      2, 0, REG_EXT},

    {__LINE__, {"abc"},         {"((abc))"},        {{"abc"},{"abc"},{"abc"}},      3, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(a(b)c)"},        {{"abc"},{"abc"},{"b"}},        3, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"(a(b)c)*"},       {{"abcabc"},{"abc"},{"b"}},     3, 0, REG_EXT},
    {__LINE__, {"aba"},         {"(a).\\1"},        {{"aba"},{"a"}},                2, 0, REG_EXT},
    {__LINE__, {"aba"},         {"((a).\\2)"},      {{"aba"},{"aba"},{"a"}},        3, 0, REG_EXT},
    {__LINE__, {"aba"},         {"((a).)\\2"},      {{"aba"},{"ab"},{"a"}},         3, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"a(bc)a\\1"},      {{"abcabc"},{"bc"}},            2, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"(a(bc))\\1"},     {{"abcabc"},{"abc"},{"bc"}},    3, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"(a)(b)c\\1\\2"},  {{"abcab"},{"a"},{"b"}},        3, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"((a)(b)c\\2)\\3"},{{"abcab"},{"abca"},{"a"},{"b"}},3, 0, REG_EXT},
    {__LINE__, {"abcabc"},      {"(...)\\1"},       {{"abcabc"},{"abc"}},           2, 0, REG_EXT},
    {__LINE__, {"<span>abc</span>"}, {"<(span)>.*</\\1>"},
                                                    {{"<span>abc</span>"},{"span"}},2, 0, REG_EXT},
    {__LINE__, {"aaabbbbc"},    {"([a-z])\\1{3}"},  {{"bbbb"},{"b"}},               2, 0, REG_EXT},

    {__LINE__, {"ab0"},         {"\\0"},            {{"0"}},                1, 0, REG_ALL},
    {__LINE__, {"aba"},         {"\\1"},            {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"aba"},         {"\\(a\\).\\9"},    {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"aba"},         {"\\(a\\1\\)."},    {{""}},                 1,-1, REG_BRE},
    {__LINE__, {"aba"},         {"(a).\\9"},        {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"aba"},         {"(a\\1)."},        {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"abb"},         {"\\1(b)"},         {{""}},                 1,-1, REG_EXT},

    {__LINE__, {"a|b"},         {"a\\|b"},          {{"a"}},                1, 0, REG_BRE},
    {__LINE__, {"a|b"},         {"a|b"},            {{"a|b"}},              1, 0, REG_BRE},
    {__LINE__, {"a|b"},         {"a|b"},            {{"a"}},                1, 0, REG_EXT},
    {__LINE__, {"a|b"},         {"a\\|b"},          {{"a|b"}},              1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"c|b"},            {{"b"}},                1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"ac|ab"},          {{"ab"}},               1, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(a|b)c"},         {{"bc"},{"b"}},         2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"^(a|b)"},         {{"a"},{"a"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(^c|^b|^a)"},     {{"a"},{"a"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(a|b|c)$"},       {{"c"},{"c"}},          2, 0, REG_EXT},
    {__LINE__, {"abc"},         {"(a$|b$|c$)"},     {{"c"},{"c"}},          2, 0, REG_EXT},
    {__LINE__, {"abc123"},      {"[A-Z]+|[0-9]+"},  {{"123"}},              1, 0, REG_EXT},
    {__LINE__, {"abc123"},      {"([A-Z]|[0-9])+"}, {{"123"},{"3"}},        2, 0, REG_EXT},
    {__LINE__, {"abc123"},      {"([A-Z]|[0-9]){4}"},{{""}},                1, 1, REG_EXT},
    {__LINE__, {"abc"},         {"(a)(c|b)(b|c)"},  {{"abc"},{"a"},{"b"},{"c"}},4, 0, REG_EXT},
    {__LINE__, {"012345678910"},{"(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)"},
               {{"12345678910"},{"1"},{"2"},{"3"},{"4"},{"5"},{"6"},{"7"},{"8"},{"9"},{"10"}},
                                                                            11,0, REG_EXT},//9を超えるサブパターンもOK

    {__LINE__, {"aabb"},        {"(a)|(\\1b)"},     {{""}},                 1,-1, REG_EXT},//エラーになるべき
    {__LINE__, {"aabb"},        {"(a)\\1|b)"},      {{"aa"},{"a"}},         2, 0, REG_EXT},
    {__LINE__, {"aabb"},        {"(c)\\1|b)"},      {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"aabb"},        {"(a)\\1|\\1b)"},   {{""}},                 1,-1, REG_EXT},
    {__LINE__, {"aabb"},        {"((a)|(b))\\1"},   {{"aa"},{"a"},{"a"},{""}}, 4, 0, REG_EXT},
    {__LINE__, {"aabb"},        {"((a)|(b))\\2"},   {{"aa"},{"a"},{"a"},{""}}, 4, 0, REG_EXT},
    {__LINE__, {"aabb"},        {"((a)|(b))\\3"},   {{"bb"},{"b"},{""},{"b"}}, 4, 0, REG_EXT},
    {__LINE__, {"ab"},          {"((a)|(b))\\1"},   {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"ab"},          {"((a)|(b))\\2"},   {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"ab"},          {"((a)|(b))\\3"},   {{""}},                 1, 1, REG_EXT},

    {__LINE__, {"XYZ123_"},     {"[[:upper:]]*"},   {{"XYZ"}},              1, 0, REG_ALL},
    {__LINE__, {"abcXYZ123_"},  {"[[:upper:][:lower:]]*"}, {{"abcXYZ"}},    1, 0, REG_ALL},
    {__LINE__, {"abcXYZ123_"},  {"[^[:upper:][:lower:]]"}, {{"1"}},         1, 0, REG_ALL},
    {__LINE__, {"abcXYZ123_"},  {"[[:alpha:]]*"},   {{"abcXYZ"}},           1, 0, REG_ALL},
    {__LINE__, {"abcXYZ123_"},  {"[[:alnum:]]*"},   {{"abcXYZ123"}},        1, 0, REG_ALL},
    {__LINE__, {"<>[]_ aX1"},   { "[^[:alnum:]]*"}, {{"<>[]_ "}},           1, 0, REG_ALL},
    {__LINE__, {"abcXYZ123_"},  {"\\w*"},           {{"abcXYZ123_"}},       1, 0, REG_ALL}, //GNU
    {__LINE__, {"!$abc"},       {"\\W*"},           {{"!$"}},               1, 0, REG_ALL}, //GNU
    {__LINE__, {"x123ABCdefx"}, {"x[[:digit:]]*"},  {{"x123"}},             1, 0, REG_ALL},
    {__LINE__, {"x123ABCdefx"}, {"x[[:xdigit:]]*"}, {{"x123ABCdef"}},       1, 0, REG_ALL},
    {__LINE__, {"[:-+a]"},      {"[[:punct:]]*"},   {{"[:-+"}},             1, 0, REG_ALL},
    {__LINE__, {" \tz"},        {"[[:blank:]]*"},   {{" \t"}},              1, 0, REG_ALL},
    {__LINE__, {" \t\n\r\f\vz"},{"[[:space:]]*"},   {{" \t\n\r\f\v"}},      1, 0, REG_ALL},
    {__LINE__, {" \t\n\r\f\vz"},{"\\s*"},           {{" \t\n\r\f\v"}},      1, 0, REG_ALL}, //GNU
    {__LINE__, {"abc123 "},     {"\\S*"},           {{"abc123"}},           1, 0, REG_ALL}, //GNU
    {__LINE__, {"\01\177"},     {"[[:cntrl:]]*"},   {{"\01\177"}},          1, 0, REG_ALL},
    {__LINE__, {"abc \t"},      {"[[:graph:]]*"},   {{"abc"}},              1, 0, REG_ALL},
    {__LINE__, {"abc \t"},      {"[[:print:]]*"},   {{"abc "}},             1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[:alpha:]*"},     {{"a"}},                1, 0, REG_ALL},
    {__LINE__, {"abc"},         {"[[:Alpha:]]*"},   {{""}},                 1,-1, REG_ALL|REG_ICASE},
    {__LINE__, {"abc"},         {"[[:alpha]]*"},    {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"abc"},         {"[[:alpha:]"},     {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"abc"},         {"[[:alpha:]-z]"},  {{""}},                 1,-1, REG_ALL},
    {__LINE__, {"a\177c"},      {"[^[:alpha:]]"},   {{"\177"}},             1, 0, REG_ALL},

//  REG_ICASE
    {__LINE__, {"aBc"},         {"aBc"},            {{"aBc"}},              1, 0, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"Abc"},            {{"aBc"}},              1, 0, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"[a-z]*"},         {{"aBc"}},              1, 0, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"[^a-z]+"},        {{""}},                 1, 1, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"[^A-Z]+"},        {{""}},                 1, 1, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"[[:lower:]]*"},   {{"aBc"}},              1, 0, REG_ALL|REG_ICASE},
    {__LINE__, {"aBc"},         {"[[:alpha:]]*"},   {{"aBc"}},              1, 0, REG_ALL|REG_ICASE},

//  REG_NEWLINE
    {__LINE__, {"abc\n"},       {"c\n"},            {{"c\n"}},              1, 0, REG_ALL},
    {__LINE__, {"abc\n"},       {"c\n"},            {{"c\n"}},              1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nc"},       {"b\nc"},           {{"b\nc"}},             1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"\nabc"},       {"\na"},            {{"\na"}},              1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"^x"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"^x"},             {{"x"}},                1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"b^x"},            {{""}},                 1, 1, REG_ALL|REG_NEWLINE},
    {__LINE__, {"\nxy"},        {"^x"},             {{"x"}},                1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"b$"},             {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"b$"},             {{"b"}},                1, 0, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"b$x"},            {{""}},                 1, 1, REG_ALL|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"b$^x"},           {{""}},                 1, 1, REG_ALL|REG_NEWLINE},
    {__LINE__, {"a\nb"},        {"a$\n^b"},         {{""}},                 1, 1, REG_BRE   |REG_NEWLINE},
    {__LINE__, {"a\nb"},        {"a$\n^b"},         {{"a\nb"}},             1, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"a\nb"},        {"a$^b"},           {{""}},                 1, 1, REG_EXT|REG_NEWLINE},

    {__LINE__, {"ab\nxy"},      {"\\(^x\\)y"},      {{"xy"},{"x"}},         2, 0, REG_BRE   |REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(^x)y"},          {{"xy"},{"x"}},         2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"\\(b$\\)\nx"},    {{"b\nx"},{"b"}},       2, 0, REG_BRE   |REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(b$)\nx"},        {{"b\nx"},{"b"}},       2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"^(x)y"},          {{"xy"},{"x"}},         2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(b)$"},           {{"b"},{"b"}},          2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"^^xy"},           {{"xy"}},               1, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"ab$$"},           {{"ab"}},               1, 0, REG_EXT|REG_NEWLINE},

    {__LINE__, {"xy"},          {"((^x)y)"},        {{"xy"},{"xy"},{"x"}},  3, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"\nxy"},        {"(^x)y"},          {{"xy"},{"x"}},         2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"\nxy"},        {"((^x)y)"},        {{"xy"},{"xy"},{"x"}},  3, 0, REG_EXT|REG_NEWLINE},

    {__LINE__, {"ab\nxy"},      {"^xz|^xy"},        {{"xy"}},               1, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"^(xz|xy)"},       {{"xy"},{"xy"}},        2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(^xy|z)"},        {{"xy"},{"xy"}},        2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxyz"},     {"((^xy|z)z)$"},    {{"xyz"},{"xyz"},{"xy"}},3, 0, REG_EXT|REG_NEWLINE},

    {__LINE__, {"ab\nxy"},      {"ab$|az$"},        {{"ab"}},               1, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(ab|az)$"},       {{"ab"},{"ab"}},        2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"ab\nxy"},      {"(ab$|az$)"},      {{"ab"},{"ab"}},        2, 0, REG_EXT|REG_NEWLINE},
    {__LINE__, {"0ab\nxy"},     {"^(0(ab$|az$))"},  {{"0ab"},{"0ab"},{"ab"}},3, 0, REG_EXT|REG_NEWLINE},

    {__LINE__, {"ab\nxy"},      {"ab."},            {{"ab\n"}},             1, 0, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"ab."},            {{""}},                 1, 1, REG_ALL|REG_NEWLINE}, //.は\nにマッチしない
    {__LINE__, {"ab\nxy"},      {"ab[^a-z]"},       {{"ab\n"}},             1, 0, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"ab[^a-z]"},       {{""}},                 1, 1, REG_ALL|REG_NEWLINE}, //[^...]は\nにマッチしない
    {__LINE__, {"ab\nxy"},      {"ab[\n]"},         {{"ab\n"}},             1, 0, REG_ALL|REG_NEWLINE},

//  REG_NOTBOL,REG_NOTEOL
    {__LINE__, {"ab\nxy"},      {"^ab"},            {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"^ab"},            {{""}},                 1, 1, REG_ALL,REG_NOTBOL},  //文字列の開始を^にマッチさせない
    {__LINE__, {"ab\nxy"},      {"^xy"},            {{"xy"}},               1, 0, REG_ALL|REG_NEWLINE,REG_NOTBOL},
    {__LINE__, {"ab\nxy"},      {"xy$"},            {{"xy"}},               1, 0, REG_ALL},
    {__LINE__, {"ab\nxy"},      {"xy$"},            {{""}},                 1, 1, REG_ALL,REG_NOTEOL},  //文字列の最後を$にマッチさせない
    {__LINE__, {"ab\nxy"},      {"ab$"},            {{"ab"}},               1, 0, REG_ALL|REG_NEWLINE,REG_NOTEOL},

//   no.        text,tlen,       regexp,rlen,        {bstr,len},...         nmatch,expect,cflags,eflags,on_syntax,off_syntax,start,end
//  REG_STARTEND
    {__LINE__, {"aabbcc"},      {"bb"},             {{"bb"}},               1, 0, REG_ALL},
    {__LINE__, {"aabbcc"},      {"bb"},             {{"bb"}},               1, 0, REG_ALL,REG_STARTEND},
    {__LINE__, {"aabbcc"},      {"b*"},             {{""}},                 1, 0, REG_ALL},
    {__LINE__, {"aabbcc"},      {"b*"},             {{"bb"}},               1, 0, REG_ALL,REG_STARTEND,0,0,{2}},

//  \0を含む処理
    {__LINE__, {"ab\0cd",5},    {"b\0c",3},         {{"b\0c",3}},           1, 0, REG_ALL},
    {__LINE__, {"ab\0cd",5},    {"b.c",3},          {{""}},                 1, 1, REG_ALL}, //デフォルトでは.は\0にはマッチしない
    {__LINE__, {"ab\0cd",5},    {"b.c",3},          {{"b\0c",3}},           1, 0, REG_ALL,0,0,RE_DOT_NOT_NULL}, //.を\0にマッチさせる
    {__LINE__, {"ab\0\0cd",6},  {"b\0*c",4},        {{"b\0\0c",4}},         1, 0, REG_ALL},
    {__LINE__, {"ab\0cd",5},    {"(b\0c)",5},       {{"b\0c",3},{"b\0c",3}},2, 0, REG_EXT},
    {__LINE__, {"ab\0cd",5},    {"b(\0)c",5},       {{"b\0c",3},{"\0",1}},  2, 0, REG_EXT},
    {__LINE__, {"\0\01a",3},    {"[[:cntrl:]]*",0}, {{"\0\01",2}},          1, 0, REG_ALL},
//text_endのオーバーランチェック
    {__LINE__, {"abc",2},       {"abc"},            {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"あい",3},      {"あい"},           {{""}},                 1, 1, REG_ALL},
#ifdef REG_ENABLE_UTF8
    {__LINE__, {"abc",2},       {"ab."},            {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"あ",1},        {"."},              {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"あ"},          {"あ",1},           {{"あ",1}},             1, 0, REG_ALL},
#endif //REG_ENABLE_UTF8
    {__LINE__, {"abc",2},       {"ab(c)"},          {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"aba",2},       {"(a)b\\1"},        {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"a\n",1},       {"^"},              {{""}},                 1, 1, REG_ALL|REG_NEWLINE,REG_NOTBOL},
    {__LINE__, {"a\n",1},       {"a$"},             {{""}},                 1, 1, REG_ALL|REG_NEWLINE,REG_NOTEOL},
    {__LINE__, {"a,c",2},       {",\\<"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc",2},       {"ab\\>"},          {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"a,c",2},       {",\\b"},           {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"abc",2},       {"ab\\b"},          {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc",2},       {"ab\\b"},          {{"ab"}},               1, 0, REG_ALL},
    {__LINE__, {"abc",2},       {"ab\\B"},          {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"aaa",2},       {"a{3}"},           {{""}},                 1, 1, REG_EXT},

//  Word
    {__LINE__, {"scan can."},   {"\\<can"},         {{"can"}},              1, 0, REG_ALL},
    {__LINE__, {"scan can."},   {"\\<scan"},        {{"scan"}},             1, 0, REG_ALL},
    {__LINE__, {"12s _9"},      {"\\<12"},          {{"12"}},               1, 0, REG_ALL},
    {__LINE__, {"12s _9"},      {"\\<_"},           {{"_"}},                1, 0, REG_ALL},
    {__LINE__, {"begin end"},   {"\\<\\w{3}\\>"},   {{"end"}},              1, 0, REG_EXT},
    {__LINE__, {"begin end"},   {"\\b\\w{3}\\b"},   {{"end"}},              1, 0, REG_EXT},
    {__LINE__, {"canCan"},      {"\\Bcan"},         {{"Can"}},              1, 0, REG_ALL|REG_ICASE},
    {__LINE__, {"canCan"},      {"can\\Bcan"},      {{"canCan"}},           1, 0, REG_ALL|REG_ICASE},

    {__LINE__, {"A\ncan\nZ"} ,  {"\\<can\\>"},      {{"can"}},              1, 0, REG_ALL},
    {__LINE__, {"A\nscan\nZ"} , {"\\<can\\>"},      {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"A\ncan\nZ"} ,  {"\\<(can)\\>"},    {{"can"},{"can"}},      2, 0, REG_EXT},
    {__LINE__, {"A\ncan\nZ"} ,  {"(\\<can\\>)"},    {{"can"},{"can"}},      2, 0, REG_EXT},

    {__LINE__, {"begin end"},   {"\\`\\w+"},        {{"begin"}},            1, 0, REG_EXT},
    {__LINE__, {"can Can"},     {"\\`Can"},         {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"can\nCan"},    {"\\`Can"},         {{""}},                 1, 1, REG_ALL},
    {__LINE__, {"begin end"},   {"\\w+\\'"},        {{"end"}},              1, 0, REG_EXT},

//  UTF-8
#ifdef REG_ENABLE_UTF8
    {__LINE__, {"あいう"},      {"あ"},             {{"あ"}},               1, 0, REG_EXT},
    {__LINE__, {"ああう"},      {"あ*"},            {{"ああ"}},             1, 0, REG_EXT},
    {__LINE__, {"ああう"},      {"(あ)*"},          {{"ああ"}},             1, 0, REG_EXT},
    {__LINE__, {"あいう"},      {"^あ"},            {{"あ"}},               1, 0, REG_EXT},
    {__LINE__, {"あいあ"},      {"あ$"},            {{"あ"}},               1, 0, REG_EXT},
    {__LINE__, {"あいう"},      {"(あ|い)*"},       {{"あい"}},             1, 0, REG_EXT},
    {__LINE__, {"あいう"},      {".."},             {{"あい"}},             1, 0, REG_EXT},
    {__LINE__, {"あいbう"},     {"[あaい]*"},       {{"あい"}},             1, 0, REG_EXT},
    {__LINE__, {"あbいう"},     {"[^aい]*"},        {{"あb"}},              1, 0, REG_EXT},
    {__LINE__, {"あ１０"},      {"[０-９]+"},       {{"１０"}},             1, 0, REG_EXT},
    {__LINE__, {"１０あ"},      {"[^０-９]+"},      {{"あ"}},               1, 0, REG_EXT},
    {__LINE__, {"aβｆ１三あ1"},{"[[:alpha:]]+"},   {{"aβｆ１三あ"}},      1, 0, REG_EXT},
    {__LINE__, {"a1βｆ１三あ"},{"[[:alnum:]]+"},   {{"a1βｆ１三あ"}},     1, 0, REG_EXT},
    {__LINE__, {"a1βｆ１三あ"},{"\\w+"},           {{"a1βｆ１三あ"}},     1, 0, REG_EXT},
    {__LINE__, {"aβ1１三あ"},  {"[[:digit:]]+"},   {{"1"}},                1, 0, REG_EXT},
    {__LINE__, {"a1ｆ１三あ"},  {"[[:xdigit:]]+"},  {{"a1"}},               1, 0, REG_EXT},
    {__LINE__, {"aβｆ１三あ"}, {"[[:lower:]]+"},   {{"aβｆ"}},            1, 0, REG_EXT},
    {__LINE__, {"aβｆ１三あ"}, {"[[:upper:]]+"},   {{""}},                 1, 1, REG_EXT},
    {__LINE__, {"ZΣＦ１三あ"}, {"[[:upper:]]+"},   {{"ZΣＦ"}},            1, 0, REG_EXT},
    {__LINE__, {"aあ　 \t\n"},  {"[[:blank:]]+"},   {{"　 \t"}},            1, 0, REG_EXT},
    {__LINE__, {"aあ　 \t\n"},  {"[[:space:]]+"},   {{"　 \t\n"}},          1, 0, REG_EXT},
    {__LINE__, {"aあ　 \t\n"},  {"\\s+"},           {{"　 \t\n"}},          1, 0, REG_EXT},
    {__LINE__, {"aあ　 \t\n"},  {"\\S+"},           {{"aあ"}},              1, 0, REG_EXT},
    {__LINE__, {"aβ１三あ1"},  {"[[:print:]]+"},   {{"aβ１三あ1"}},       1, 0, REG_EXT},
    {__LINE__, {"aβ１三あ1"},  {"[[:graph:]]+"},   {{"aβ１三あ1"}},       1, 0, REG_EXT},
    {__LINE__, {"\01\177"},     {"[[:cntrl:]]*"},   {{"\01\177"}},          1, 0, REG_EXT},
    {__LINE__, {"[:＆＋￥a]"},  {"[[:punct:]]*"},   {{"[:＆＋￥"}},         1, 0, REG_EXT},
    {__LINE__, {"[:＆＋￥a]"},  {"\\W*"},           {{"[:＆＋￥"}},         1, 0, REG_EXT},
    {__LINE__, {"a1βｆ１三あ"},{"[[:alpha:][:digit:]]+"},
                                                    {{"a1βｆ１三あ"}},     1, 0, REG_EXT},

    {__LINE__, {"ZΣＡあ"},     {"zσａ"},          {{"ZΣＡ"}},            1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"zσａあ"},     {"ZΣＡ"},          {{"zσａ"}},            1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"ZΣＡあ"},     {"[zσａ]+"},       {{"ZΣＡ"}},            1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"zσａあ"},     {"[ZΣＡ]+"},       {{"zσａ"}},            1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"ZΣＡあ"},     {"[a-zα-σａ-ｚ]+"},{{"ZΣＡ"}},           1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"zσａあ"},     {"[A-ZΑ-ΣＡ-Ｚ]+"},{{"zσａ"}},           1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"ZΣＡあ"},     {"[[:lower:]]+"},   {{"ZΣＡあ"}},          1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"zσａあ"},     {"[[:upper:]]+"},   {{"zσａあ"}},          1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"aBβΣｂＺっ"},{"[[:lower:]]+"},   {{"aBβΣｂＺっ"}},     1, 0, REG_EXT|REG_ICASE},
    {__LINE__, {"aBc"},         {"[[:alpha:]]+"},   {{"aBc"}},              1, 0, REG_EXT|REG_ICASE},
#endif

//  {__LINE__, {"a"},           {"[^a]"},           {{""}},                 1, 1, REG_EXT|REG_DUMP},   //dumpテスト
//}
